### PR TITLE
Add a Gitter chat link to README

### PR DESCRIPTION
**Pull request by gitter-badger**
### bronson/Term-ShellUI now has a Chat Room on Gitter

@tehnick has just created a chat room. You can visit it here: [https://gitter.im/bronson/Term-ShellUI](https://gitter.im/bronson/Term-ShellUI?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds a link to your README.

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by bronson** [comment]
Hi, apparently Gitter wants:

    This application will be able to read and write all public and private repository data.

Being able to write to my public repos is very bad, and being able to read/write private ones is even worse!

Until they fix this, I can't possibly use Gitter.  Sorry.

**Comment by mydigitalself** [comment]
@bronson we only ask for this permission if you specifically enable Gitter for private repos, we do not ask for this permission by default at all.

**Comment by bronson** [comment]
@mydigitalself then what was going on there?  I should have taken a screenshot because now apparently the link is 404ing.

Hate to disagree with you but Gitter was most definitely demanding access to all public & private repos.

**Comment by mydigitalself** [comment]
@bronson you must have visited a URL of a private repo page, I can quite categorically state that our regular signup flow and participation in public chat rooms absolutely do not require private repo access.

However, what may be mildly confusing... we respect GitHub's nondisclosure of secure resources, so if you did happen to hit even a genuine 404, because we don't disclose if you've hit that 404 because the resource actually doesn't exist or because you don't have permission, we do have a little prompt ala:
http://cl.ly/image/2B3P2G3l271X

**Comment by bronson** [comment]
@mydigitalself no, I just clicked the link at the top of this page.  Copied here:

https://gitter.im/bronson/Term-ShellUI?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link

Term-ShellUI is public.

**Comment by mydigitalself** [comment]
The room doesn't exist (hence the 404 - perhaps it was deleted before you clicked on it). I assume if you visit it now you get pretty much exactly this: http://cl.ly/image/2B3P2G3l271X

And because, as I explained above, we respect GitHub's behaviour of not disclosing the 404 reason (i.e. actually not found vs permissions, we do put a little prompt there saying "If you're looking for a private repo..."

That's all I can imagine that's happened and probably been caused by someone deleting the room prior to you clicking on the link.

**Comment by bronson** [comment]
Right.  But when I clicked on the link yesterday, it existed, and I copied that text straight out of the browser window.  That's one of the permissions Gitter was demanding, word for word.

I don't understand why you're telling me this is impossible.  I only wish I'd saved you a screenshot.

**Comment by tehnick** [comment]
Hi everyone,

Yesterday when I have been creating chat room at Glitter for another project I accidentally clicked on the Term-ShellUI hyperlink and Gitter have created chat room for Term-ShellUI without any additional confirmation queries. When I noticed it I have removed this chat room.

Sorry for inconvenience.

**Comment by bronson** [comment]
No problem Boris.  This has been educational.  Hope the Gitter team can fix whatever was causing it to demand too many permissions.

**Pull request closed without merging**
